import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { config } from '../config.js';
import * as schema from './schema.js';
import fs from 'fs';
import path from 'path';

const dbDir = path.dirname(config.databasePath);
if (!fs.existsSync(dbDir)) {
  fs.mkdirSync(dbDir, { recursive: true });
}

const sqlite = new Database(config.databasePath);
sqlite.pragma('journal_mode = WAL');
sqlite.pragma('foreign_keys = ON');

export const db = drizzle(sqlite, { schema });

export function initDb() {
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS admins (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

    CREATE TABLE IF NOT EXISTS domains (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      domain TEXT NOT NULL UNIQUE,
      is_active INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

    CREATE TABLE IF NOT EXISTS links (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      slug TEXT NOT NULL UNIQUE,
      target_url TEXT NOT NULL,
      template_id TEXT NOT NULL,
      title TEXT,
      template_options TEXT,
      gps_mode TEXT NOT NULL DEFAULT 'optional',
      domain_id INTEGER REFERENCES domains(id) ON DELETE SET NULL,
      is_active INTEGER NOT NULL DEFAULT 1,
      visit_count INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

    CREATE TABLE IF NOT EXISTS visitors (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      link_id INTEGER NOT NULL REFERENCES links(id) ON DELETE CASCADE,
      ip TEXT,
      user_agent TEXT,
      browser TEXT,
      browser_version TEXT,
      os TEXT,
      platform TEXT,
      cpu_cores INTEGER,
      ram INTEGER,
      screen_width INTEGER,
      screen_height INTEGER,
      color_depth INTEGER,
      gpu_vendor TEXT,
      gpu_renderer TEXT,
      canvas_hash TEXT,
      touch_support INTEGER,
      language TEXT,
      timezone TEXT,
      cookies_enabled INTEGER,
      do_not_track INTEGER,
      audio_hash TEXT,
      webgl_max_texture_size INTEGER,
      webgl_max_viewport_width INTEGER,
      webgl_max_viewport_height INTEGER,
      webgl_extensions TEXT,
      webgl_shader_precision TEXT,
      connection_type TEXT,
      downlink_speed REAL,
      network_rtt INTEGER,
      save_data INTEGER,
      camera_count INTEGER,
      microphone_count INTEGER,
      speaker_count INTEGER,
      screen_avail_width INTEGER,
      screen_avail_height INTEGER,
      pixel_depth INTEGER,
      device_pixel_ratio REAL,
      screen_orientation TEXT,
      vendor TEXT,
      is_online INTEGER,
      pdf_viewer_enabled INTEGER,
      webdriver_detected INTEGER,
      storage_quota REAL,
      storage_usage REAL,
      installed_languages TEXT,
      perm_geolocation TEXT,
      perm_camera TEXT,
      perm_microphone TEXT,
      perm_notifications TEXT,
      referrer TEXT,
      page_load_time INTEGER,
      ad_blocker_detected INTEGER,
      incognito_detected INTEGER,
      local_ips TEXT,
      speech_voices_hash TEXT,
      detected_fonts TEXT,
      prefers_color_scheme TEXT,
      prefers_reduced_motion INTEGER,
      hdr_support INTEGER,
      forced_colors INTEGER,
      pointer_type TEXT,
      color_gamut TEXT,
      client_arch TEXT,
      client_bitness TEXT,
      client_platform_version TEXT,
      client_model TEXT,
      battery_level REAL,
      battery_charging INTEGER,
      intl_locale_fingerprint TEXT,
      js_heap_size_limit REAL,
      multi_monitor INTEGER,
      max_touch_points INTEGER,
      installed_plugins TEXT,
      api_support TEXT,
      timezone_offset INTEGER,
      observes_dst INTEGER,
      navigation_type TEXT,
      keyboard_layout TEXT,
      math_fingerprint TEXT,
      dom_rect_fingerprint TEXT,
      media_codec_fingerprint TEXT,
      audio_context_props TEXT,
      css_system_color_fingerprint TEXT,
      webgl2_fingerprint TEXT,
      svg_filter_fingerprint TEXT,
      error_message_fingerprint TEXT,
      wasm_capabilities TEXT,
      scrollbar_width INTEGER,
      timer_resolution TEXT,
      text_metrics_fingerprint TEXT,
      date_to_string_fingerprint TEXT,
      emoji_support_fingerprint TEXT,
      perf_entry_types TEXT,
      security_context TEXT,
      css_support_fingerprint TEXT,
      line_break_fingerprint TEXT,
      mouse_data TEXT,
      click_data TEXT,
      scroll_data TEXT,
      touch_data TEXT,
      motion_data TEXT,
      dwell_time INTEGER,
      focus_data TEXT,
      bot_score INTEGER,
      vpn_detected INTEGER,
      privacy_score INTEGER,
      device_tier TEXT,
      browser_authenticity TEXT,
      uniqueness_score INTEGER,
      location_consistency TEXT,
      human_score INTEGER,
      user_profile TEXT,
      risk_flags TEXT,
      gps_granted INTEGER NOT NULL DEFAULT 0,
      latitude REAL,
      longitude REAL,
      accuracy REAL,
      altitude REAL,
      altitude_accuracy REAL,
      speed REAL,
      heading REAL,
      ip_city TEXT,
      ip_region TEXT,
      ip_country TEXT,
      ip_country_code TEXT,
      ip_lat REAL,
      ip_lon REAL,
      ip_isp TEXT,
      created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );
  `);

  // Migrations for existing databases
  const newLinkCols = [
    'template_options TEXT',
    "gps_mode TEXT NOT NULL DEFAULT 'optional'",
    'domain_id INTEGER REFERENCES domains(id) ON DELETE SET NULL',
  ];
  for (const col of newLinkCols) {
    try { sqlite.exec(`ALTER TABLE links ADD COLUMN ${col}`); } catch {}
  }

  const newVisitorCols = [
    'audio_hash TEXT',
    'webgl_max_texture_size INTEGER',
    'webgl_max_viewport_width INTEGER',
    'webgl_max_viewport_height INTEGER',
    'webgl_extensions TEXT',
    'webgl_shader_precision TEXT',
    'connection_type TEXT',
    'downlink_speed REAL',
    'network_rtt INTEGER',
    'save_data INTEGER',
    'camera_count INTEGER',
    'microphone_count INTEGER',
    'speaker_count INTEGER',
    'screen_avail_width INTEGER',
    'screen_avail_height INTEGER',
    'pixel_depth INTEGER',
    'device_pixel_ratio REAL',
    'screen_orientation TEXT',
    'vendor TEXT',
    'is_online INTEGER',
    'pdf_viewer_enabled INTEGER',
    'webdriver_detected INTEGER',
    'storage_quota REAL',
    'storage_usage REAL',
    'installed_languages TEXT',
    'perm_geolocation TEXT',
    'perm_camera TEXT',
    'perm_microphone TEXT',
    'perm_notifications TEXT',
    'referrer TEXT',
    'page_load_time INTEGER',
    'ad_blocker_detected INTEGER',
    'incognito_detected INTEGER',
    'ip_country_code TEXT',
    'local_ips TEXT',
    'speech_voices_hash TEXT',
    'detected_fonts TEXT',
    'prefers_color_scheme TEXT',
    'prefers_reduced_motion INTEGER',
    'hdr_support INTEGER',
    'forced_colors INTEGER',
    'pointer_type TEXT',
    'color_gamut TEXT',
    'client_arch TEXT',
    'client_bitness TEXT',
    'client_platform_version TEXT',
    'client_model TEXT',
    'battery_level REAL',
    'battery_charging INTEGER',
    'intl_locale_fingerprint TEXT',
    'js_heap_size_limit REAL',
    'multi_monitor INTEGER',
    'max_touch_points INTEGER',
    'installed_plugins TEXT',
    'api_support TEXT',
    'timezone_offset INTEGER',
    'observes_dst INTEGER',
    'navigation_type TEXT',
    'keyboard_layout TEXT',
    'math_fingerprint TEXT',
    'dom_rect_fingerprint TEXT',
    'media_codec_fingerprint TEXT',
    'audio_context_props TEXT',
    'css_system_color_fingerprint TEXT',
    'webgl2_fingerprint TEXT',
    'svg_filter_fingerprint TEXT',
    'error_message_fingerprint TEXT',
    'wasm_capabilities TEXT',
    'scrollbar_width INTEGER',
    'timer_resolution TEXT',
    'text_metrics_fingerprint TEXT',
    'date_to_string_fingerprint TEXT',
    'emoji_support_fingerprint TEXT',
    'perf_entry_types TEXT',
    'security_context TEXT',
    'css_support_fingerprint TEXT',
    'line_break_fingerprint TEXT',
    // Behavioral biometrics
    'mouse_data TEXT',
    'click_data TEXT',
    'scroll_data TEXT',
    'touch_data TEXT',
    'motion_data TEXT',
    'dwell_time INTEGER',
    'focus_data TEXT',
    // Server-side analysis
    'bot_score INTEGER',
    'vpn_detected INTEGER',
    'privacy_score INTEGER',
    'device_tier TEXT',
    'browser_authenticity TEXT',
    'uniqueness_score INTEGER',
    'location_consistency TEXT',
    'human_score INTEGER',
    'user_profile TEXT',
    'risk_flags TEXT',
  ];
  for (const col of newVisitorCols) {
    try { sqlite.exec(`ALTER TABLE visitors ADD COLUMN ${col}`); } catch {}
  }
}
