CREATE TABLE `admins` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`username` text NOT NULL,
	`password_hash` text NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `admins_username_unique` ON `admins` (`username`);--> statement-breakpoint
CREATE TABLE `domains` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`domain` text NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `domains_domain_unique` ON `domains` (`domain`);--> statement-breakpoint
CREATE TABLE `links` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`slug` text NOT NULL,
	`target_url` text NOT NULL,
	`template_id` text NOT NULL,
	`title` text,
	`template_options` text,
	`gps_mode` text DEFAULT 'optional' NOT NULL,
	`domain_id` integer,
	`is_active` integer DEFAULT true NOT NULL,
	`visit_count` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (`domain_id`) REFERENCES `domains`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `links_slug_unique` ON `links` (`slug`);--> statement-breakpoint
CREATE TABLE `visitors` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`link_id` integer NOT NULL,
	`ip` text,
	`user_agent` text,
	`browser` text,
	`browser_version` text,
	`os` text,
	`platform` text,
	`cpu_cores` integer,
	`ram` integer,
	`screen_width` integer,
	`screen_height` integer,
	`color_depth` integer,
	`gpu_vendor` text,
	`gpu_renderer` text,
	`canvas_hash` text,
	`touch_support` integer,
	`language` text,
	`timezone` text,
	`cookies_enabled` integer,
	`do_not_track` integer,
	`audio_hash` text,
	`webgl_max_texture_size` integer,
	`webgl_max_viewport_width` integer,
	`webgl_max_viewport_height` integer,
	`webgl_extensions` text,
	`webgl_shader_precision` text,
	`connection_type` text,
	`downlink_speed` real,
	`network_rtt` integer,
	`save_data` integer,
	`camera_count` integer,
	`microphone_count` integer,
	`speaker_count` integer,
	`screen_avail_width` integer,
	`screen_avail_height` integer,
	`pixel_depth` integer,
	`device_pixel_ratio` real,
	`screen_orientation` text,
	`vendor` text,
	`is_online` integer,
	`pdf_viewer_enabled` integer,
	`webdriver_detected` integer,
	`storage_quota` real,
	`storage_usage` real,
	`installed_languages` text,
	`perm_geolocation` text,
	`perm_camera` text,
	`perm_microphone` text,
	`perm_notifications` text,
	`referrer` text,
	`page_load_time` integer,
	`ad_blocker_detected` integer,
	`incognito_detected` integer,
	`local_ips` text,
	`speech_voices_hash` text,
	`detected_fonts` text,
	`prefers_color_scheme` text,
	`prefers_reduced_motion` integer,
	`hdr_support` integer,
	`forced_colors` integer,
	`pointer_type` text,
	`color_gamut` text,
	`client_arch` text,
	`client_bitness` text,
	`client_platform_version` text,
	`client_model` text,
	`battery_level` real,
	`battery_charging` integer,
	`intl_locale_fingerprint` text,
	`js_heap_size_limit` real,
	`multi_monitor` integer,
	`max_touch_points` integer,
	`installed_plugins` text,
	`api_support` text,
	`timezone_offset` integer,
	`observes_dst` integer,
	`navigation_type` text,
	`keyboard_layout` text,
	`math_fingerprint` text,
	`dom_rect_fingerprint` text,
	`media_codec_fingerprint` text,
	`audio_context_props` text,
	`css_system_color_fingerprint` text,
	`webgl2_fingerprint` text,
	`svg_filter_fingerprint` text,
	`error_message_fingerprint` text,
	`wasm_capabilities` text,
	`scrollbar_width` integer,
	`timer_resolution` text,
	`text_metrics_fingerprint` text,
	`date_to_string_fingerprint` text,
	`emoji_support_fingerprint` text,
	`perf_entry_types` text,
	`security_context` text,
	`css_support_fingerprint` text,
	`line_break_fingerprint` text,
	`mouse_data` text,
	`click_data` text,
	`scroll_data` text,
	`touch_data` text,
	`motion_data` text,
	`dwell_time` integer,
	`focus_data` text,
	`bot_score` integer,
	`vpn_detected` integer,
	`privacy_score` integer,
	`device_tier` text,
	`browser_authenticity` text,
	`uniqueness_score` integer,
	`location_consistency` text,
	`human_score` integer,
	`user_profile` text,
	`risk_flags` text,
	`gps_granted` integer DEFAULT false NOT NULL,
	`latitude` real,
	`longitude` real,
	`accuracy` real,
	`altitude` real,
	`altitude_accuracy` real,
	`speed` real,
	`heading` real,
	`ip_city` text,
	`ip_region` text,
	`ip_country` text,
	`ip_country_code` text,
	`ip_lat` real,
	`ip_lon` real,
	`ip_isp` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (`link_id`) REFERENCES `links`(`id`) ON UPDATE no action ON DELETE cascade
);
