CREATE TABLE "audit_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"action" text NOT NULL,
	"target_type" text,
	"target_id" integer,
	"details" text,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "domains" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"domain" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "domains_domain_unique" UNIQUE("domain")
);
--> statement-breakpoint
CREATE TABLE "links" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"slug" text NOT NULL,
	"target_url" text NOT NULL,
	"template_id" text NOT NULL,
	"title" text,
	"template_options" text,
	"gps_mode" text DEFAULT 'optional' NOT NULL,
	"domain_id" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"visit_count" integer DEFAULT 0 NOT NULL,
	"expires_at" text,
	"max_visits" integer,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "links_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text,
	"email" text,
	"display_name" text NOT NULL,
	"password_hash" text,
	"google_subject" text,
	"avatar_url" text,
	"role" text DEFAULT 'user' NOT NULL,
	"token_version" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_google_subject_unique" UNIQUE("google_subject")
);
--> statement-breakpoint
CREATE TABLE "visitors" (
	"id" serial PRIMARY KEY NOT NULL,
	"link_id" integer NOT NULL,
	"ip" text,
	"user_agent" text,
	"browser" text,
	"browser_version" text,
	"os" text,
	"platform" text,
	"cpu_cores" integer,
	"ram" integer,
	"screen_width" integer,
	"screen_height" integer,
	"color_depth" integer,
	"gpu_vendor" text,
	"gpu_renderer" text,
	"canvas_hash" text,
	"touch_support" boolean,
	"language" text,
	"timezone" text,
	"cookies_enabled" boolean,
	"do_not_track" boolean,
	"audio_hash" text,
	"webgl_max_texture_size" integer,
	"webgl_max_viewport_width" integer,
	"webgl_max_viewport_height" integer,
	"webgl_extensions" text,
	"webgl_shader_precision" text,
	"connection_type" text,
	"downlink_speed" real,
	"network_rtt" integer,
	"save_data" boolean,
	"camera_count" integer,
	"microphone_count" integer,
	"speaker_count" integer,
	"screen_avail_width" integer,
	"screen_avail_height" integer,
	"pixel_depth" integer,
	"device_pixel_ratio" real,
	"screen_orientation" text,
	"vendor" text,
	"is_online" boolean,
	"pdf_viewer_enabled" boolean,
	"webdriver_detected" boolean,
	"storage_quota" real,
	"storage_usage" real,
	"installed_languages" text,
	"perm_geolocation" text,
	"perm_camera" text,
	"perm_microphone" text,
	"perm_notifications" text,
	"referrer" text,
	"page_load_time" integer,
	"ad_blocker_detected" boolean,
	"incognito_detected" boolean,
	"local_ips" text,
	"speech_voices_hash" text,
	"detected_fonts" text,
	"prefers_color_scheme" text,
	"prefers_reduced_motion" boolean,
	"hdr_support" boolean,
	"forced_colors" boolean,
	"pointer_type" text,
	"color_gamut" text,
	"client_arch" text,
	"client_bitness" text,
	"client_platform_version" text,
	"client_model" text,
	"battery_level" real,
	"battery_charging" boolean,
	"intl_locale_fingerprint" text,
	"js_heap_size_limit" real,
	"multi_monitor" boolean,
	"max_touch_points" integer,
	"installed_plugins" text,
	"api_support" text,
	"timezone_offset" integer,
	"observes_dst" boolean,
	"navigation_type" text,
	"keyboard_layout" text,
	"math_fingerprint" text,
	"dom_rect_fingerprint" text,
	"media_codec_fingerprint" text,
	"audio_context_props" text,
	"css_system_color_fingerprint" text,
	"webgl2_fingerprint" text,
	"svg_filter_fingerprint" text,
	"error_message_fingerprint" text,
	"wasm_capabilities" text,
	"scrollbar_width" integer,
	"timer_resolution" text,
	"text_metrics_fingerprint" text,
	"date_to_string_fingerprint" text,
	"emoji_support_fingerprint" text,
	"perf_entry_types" text,
	"security_context" text,
	"css_support_fingerprint" text,
	"line_break_fingerprint" text,
	"mouse_data" text,
	"click_data" text,
	"scroll_data" text,
	"touch_data" text,
	"motion_data" text,
	"dwell_time" integer,
	"focus_data" text,
	"bot_score" integer,
	"vpn_detected" boolean,
	"privacy_score" integer,
	"device_tier" text,
	"browser_authenticity" text,
	"uniqueness_score" integer,
	"location_consistency" text,
	"human_score" integer,
	"user_profile" text,
	"risk_flags" text,
	"gps_granted" boolean DEFAULT false NOT NULL,
	"latitude" real,
	"longitude" real,
	"accuracy" real,
	"altitude" real,
	"altitude_accuracy" real,
	"speed" real,
	"heading" real,
	"ip_city" text,
	"ip_region" text,
	"ip_country" text,
	"ip_country_code" text,
	"ip_lat" real,
	"ip_lon" real,
	"ip_isp" text,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhooks" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"url" text NOT NULL,
	"events" text NOT NULL,
	"secret" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "domains" ADD CONSTRAINT "domains_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "links" ADD CONSTRAINT "links_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "links" ADD CONSTRAINT "links_domain_id_domains_id_fk" FOREIGN KEY ("domain_id") REFERENCES "public"."domains"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "visitors" ADD CONSTRAINT "visitors_link_id_links_id_fk" FOREIGN KEY ("link_id") REFERENCES "public"."links"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_logs_user_id_idx" ON "audit_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "domains_user_id_idx" ON "domains" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "links_user_id_idx" ON "links" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_google_subject_idx" ON "users" USING btree ("google_subject");--> statement-breakpoint
CREATE INDEX "visitors_link_id_idx" ON "visitors" USING btree ("link_id");--> statement-breakpoint
CREATE INDEX "visitors_created_at_idx" ON "visitors" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "webhooks_user_id_idx" ON "webhooks" USING btree ("user_id");