import { sql } from 'drizzle-orm';
import { boolean, index, integer, pgTable, real, serial, text } from 'drizzle-orm/pg-core';

const timestampText = sql`(CURRENT_TIMESTAMP)::text`;

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  username: text('username').unique(),
  email: text('email').unique(),
  displayName: text('display_name').notNull(),
  passwordHash: text('password_hash'),
  googleSubject: text('google_subject').unique(),
  avatarUrl: text('avatar_url'),
  role: text('role', { enum: ['user', 'admin'] }).default('user').notNull(),
  tokenVersion: integer('token_version').default(0).notNull(),
  createdAt: text('created_at').default(timestampText).notNull(),
  updatedAt: text('updated_at').default(timestampText).notNull(),
}, (table) => [
  index('users_email_idx').on(table.email),
  index('users_google_subject_idx').on(table.googleSubject),
]);

export const domains = pgTable('domains', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  domain: text('domain').notNull().unique(),
  isActive: boolean('is_active').default(true).notNull(),
  createdAt: text('created_at').default(timestampText).notNull(),
}, (table) => [index('domains_user_id_idx').on(table.userId)]);

export const links = pgTable('links', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  slug: text('slug').notNull().unique(),
  targetUrl: text('target_url').notNull(),
  templateId: text('template_id').notNull(),
  title: text('title'),
  templateOptions: text('template_options'),
  gpsMode: text('gps_mode').notNull().default('optional'),
  domainId: integer('domain_id').references(() => domains.id, { onDelete: 'set null' }),
  isActive: boolean('is_active').default(true).notNull(),
  visitCount: integer('visit_count').default(0).notNull(),
  expiresAt: text('expires_at'),
  maxVisits: integer('max_visits'),
  createdAt: text('created_at').default(timestampText).notNull(),
}, (table) => [index('links_user_id_idx').on(table.userId)]);

export const visitors = pgTable('visitors', {
  id: serial('id').primaryKey(),
  linkId: integer('link_id').notNull().references(() => links.id, { onDelete: 'cascade' }),
  ip: text('ip'),
  userAgent: text('user_agent'),
  browser: text('browser'),
  browserVersion: text('browser_version'),
  os: text('os'),
  platform: text('platform'),
  cpuCores: integer('cpu_cores'),
  ram: integer('ram'),
  screenWidth: integer('screen_width'),
  screenHeight: integer('screen_height'),
  colorDepth: integer('color_depth'),
  gpuVendor: text('gpu_vendor'),
  gpuRenderer: text('gpu_renderer'),
  canvasHash: text('canvas_hash'),
  touchSupport: boolean('touch_support'),
  language: text('language'),
  timezone: text('timezone'),
  cookiesEnabled: boolean('cookies_enabled'),
  doNotTrack: boolean('do_not_track'),
  audioHash: text('audio_hash'),
  webglMaxTextureSize: integer('webgl_max_texture_size'),
  webglMaxViewportWidth: integer('webgl_max_viewport_width'),
  webglMaxViewportHeight: integer('webgl_max_viewport_height'),
  webglExtensions: text('webgl_extensions'),
  webglShaderPrecision: text('webgl_shader_precision'),
  connectionType: text('connection_type'),
  downlinkSpeed: real('downlink_speed'),
  networkRtt: integer('network_rtt'),
  saveData: boolean('save_data'),
  cameraCount: integer('camera_count'),
  microphoneCount: integer('microphone_count'),
  speakerCount: integer('speaker_count'),
  screenAvailWidth: integer('screen_avail_width'),
  screenAvailHeight: integer('screen_avail_height'),
  pixelDepth: integer('pixel_depth'),
  devicePixelRatio: real('device_pixel_ratio'),
  screenOrientation: text('screen_orientation'),
  vendor: text('vendor'),
  isOnline: boolean('is_online'),
  pdfViewerEnabled: boolean('pdf_viewer_enabled'),
  webdriverDetected: boolean('webdriver_detected'),
  storageQuota: real('storage_quota'),
  storageUsage: real('storage_usage'),
  installedLanguages: text('installed_languages'),
  permGeolocation: text('perm_geolocation'),
  permCamera: text('perm_camera'),
  permMicrophone: text('perm_microphone'),
  permNotifications: text('perm_notifications'),
  referrer: text('referrer'),
  pageLoadTime: integer('page_load_time'),
  adBlockerDetected: boolean('ad_blocker_detected'),
  incognitoDetected: boolean('incognito_detected'),
  localIPs: text('local_ips'),
  speechVoicesHash: text('speech_voices_hash'),
  detectedFonts: text('detected_fonts'),
  prefersColorScheme: text('prefers_color_scheme'),
  prefersReducedMotion: boolean('prefers_reduced_motion'),
  hdrSupport: boolean('hdr_support'),
  forcedColors: boolean('forced_colors'),
  pointerType: text('pointer_type'),
  colorGamut: text('color_gamut'),
  clientArch: text('client_arch'),
  clientBitness: text('client_bitness'),
  clientPlatformVersion: text('client_platform_version'),
  clientModel: text('client_model'),
  batteryLevel: real('battery_level'),
  batteryCharging: boolean('battery_charging'),
  intlLocaleFingerprint: text('intl_locale_fingerprint'),
  jsHeapSizeLimit: real('js_heap_size_limit'),
  multiMonitor: boolean('multi_monitor'),
  maxTouchPoints: integer('max_touch_points'),
  installedPlugins: text('installed_plugins'),
  apiSupport: text('api_support'),
  timezoneOffset: integer('timezone_offset'),
  observesDst: boolean('observes_dst'),
  navigationType: text('navigation_type'),
  keyboardLayout: text('keyboard_layout'),
  mathFingerprint: text('math_fingerprint'),
  domRectFingerprint: text('dom_rect_fingerprint'),
  mediaCodecFingerprint: text('media_codec_fingerprint'),
  audioContextProps: text('audio_context_props'),
  cssSystemColorFingerprint: text('css_system_color_fingerprint'),
  webgl2Fingerprint: text('webgl2_fingerprint'),
  svgFilterFingerprint: text('svg_filter_fingerprint'),
  errorMessageFingerprint: text('error_message_fingerprint'),
  wasmCapabilities: text('wasm_capabilities'),
  scrollbarWidth: integer('scrollbar_width'),
  timerResolution: text('timer_resolution'),
  textMetricsFingerprint: text('text_metrics_fingerprint'),
  dateToStringFingerprint: text('date_to_string_fingerprint'),
  emojiSupportFingerprint: text('emoji_support_fingerprint'),
  perfEntryTypes: text('perf_entry_types'),
  securityContext: text('security_context'),
  cssSupportFingerprint: text('css_support_fingerprint'),
  lineBreakFingerprint: text('line_break_fingerprint'),
  mouseData: text('mouse_data'),
  clickData: text('click_data'),
  scrollData: text('scroll_data'),
  touchData: text('touch_data'),
  motionData: text('motion_data'),
  dwellTime: integer('dwell_time'),
  focusData: text('focus_data'),
  botScore: integer('bot_score'),
  vpnDetected: boolean('vpn_detected'),
  privacyScore: integer('privacy_score'),
  deviceTier: text('device_tier'),
  browserAuthenticity: text('browser_authenticity'),
  uniquenessScore: integer('uniqueness_score'),
  locationConsistency: text('location_consistency'),
  humanScore: integer('human_score'),
  userProfile: text('user_profile'),
  riskFlags: text('risk_flags'),
  gpsGranted: boolean('gps_granted').default(false).notNull(),
  latitude: real('latitude'),
  longitude: real('longitude'),
  accuracy: real('accuracy'),
  altitude: real('altitude'),
  altitudeAccuracy: real('altitude_accuracy'),
  speed: real('speed'),
  heading: real('heading'),
  ipCity: text('ip_city'),
  ipRegion: text('ip_region'),
  ipCountry: text('ip_country'),
  ipCountryCode: text('ip_country_code'),
  ipLat: real('ip_lat'),
  ipLon: real('ip_lon'),
  ipIsp: text('ip_isp'),
  createdAt: text('created_at').default(timestampText).notNull(),
}, (table) => [
  index('visitors_link_id_idx').on(table.linkId),
  index('visitors_created_at_idx').on(table.createdAt),
]);

export const auditLogs = pgTable('audit_logs', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').references(() => users.id, { onDelete: 'set null' }),
  action: text('action').notNull(),
  targetType: text('target_type'),
  targetId: integer('target_id'),
  details: text('details'),
  createdAt: text('created_at').default(timestampText).notNull(),
}, (table) => [
  index('audit_logs_user_id_idx').on(table.userId),
  index('audit_logs_created_at_idx').on(table.createdAt),
]);

export const webhooks = pgTable('webhooks', {
  id: serial('id').primaryKey(),
  userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  url: text('url').notNull(),
  events: text('events').notNull(),
  secret: text('secret'),
  isActive: boolean('is_active').default(true).notNull(),
  createdAt: text('created_at').default(timestampText).notNull(),
}, (table) => [index('webhooks_user_id_idx').on(table.userId)]);
